import { AgentGatewayEndpointOperations } from './agent-gateway-api.oauth-system-endpoints';
import { AgentGatewayApiTransport } from './agent-gateway-api.requests';
import type { AgentGatewayApiClientOptions } from './agent-gateway-api.types';

export type {
  GatewayApiKey,
  GatewayApiKeyListResponse,
  GatewayAuthFile,
  GatewayAuthFileBatchUploadRequest,
  GatewayAuthFileBatchUploadResponse,
  GatewayAuthFileDeleteRequest,
  GatewayAuthFileDeleteResponse,
  GatewayAuthFileListResponse,
  GatewayAuthFileModelListResponse,
  GatewayAuthFilePatchRequest,
  GatewayClearLoginStorageResponse,
  GatewayClearLogsResponse,
  GatewayClient,
  GatewayClientApiKey,
  GatewayClientApiKeyListResponse,
  GatewayClientListResponse,
  GatewayClientQuota,
  GatewayClientRequestLog,
  GatewayClientRequestLogListResponse,
  GatewayClientUsageSummary,
  GatewayConfigDiffResponse,
  GatewayConnectionProfile,
  GatewayConnectionStatusResponse,
  GatewayCreateClientApiKeyRequest,
  GatewayCreateClientApiKeyResponse,
  GatewayCreateClientRequest,
  GatewayDashboardSummaryResponse,
  GatewayGeminiCliOAuthStartResponse,
  GatewayLogFile,
  GatewayLogFileListResponse,
  GatewayManagementApiCallRequest,
  GatewayManagementApiCallResponse,
  GatewayMigrationApplyRequest,
  GatewayMigrationApplyResponse,
  GatewayMigrationPreview,
  GatewayMigrationPreviewRequest,
  GatewayOAuthCallbackRequest,
  GatewayOAuthCallbackResponse,
  GatewayOAuthModelAliasListResponse,
  GatewayOAuthStatusResponse,
  GatewayProviderKind,
  GatewayProviderOAuthStartProvider,
  GatewayProviderOAuthStartResponse,
  GatewayProviderSpecificConfigListResponse,
  GatewayProviderSpecificConfigRecord,
  GatewayQuotaDetailListResponse,
  GatewayRawConfigResponse,
  GatewayReloadConfigResponse,
  GatewayReplaceApiKeysRequest,
  GatewayRequestLogSettingResponse,
  GatewayRuntimeHealthResponse,
  GatewaySaveConnectionProfileRequest,
  GatewaySaveRawConfigRequest,
  GatewaySystemModelGroup,
  GatewaySystemModelsResponse,
  GatewaySystemVersionResponse,
  GatewayUpdateClientApiKeyRequest,
  GatewayUpdateClientQuotaRequest,
  GatewayUpdateClientRequest,
  GatewayUpdateOAuthModelAliasRulesRequest,
  GatewayUsageAnalyticsQuery,
  GatewayUsageAnalyticsResponse,
  GatewayVertexCredentialImportRequest,
  GatewayVertexCredentialImportResponse
} from './agent-gateway-api.types';

export class AgentGatewayApiClient extends AgentGatewayEndpointOperations {
  constructor(options: AgentGatewayApiClientOptions) {
    super(new AgentGatewayApiTransport(options));
  }
}
