import { z } from 'zod';

import { EvidenceRecordSchema, LearningCandidateRecordSchema } from '../memory';
import { ApprovalRecordSchema } from './governance';
import {
  AgentMessageRecordSchema,
  AgentExecutionStateSchema,
  BlackboardStateRecordSchema,
  BudgetGateStateRecordSchema,
  ComplexTaskPlanRecordSchema,
  ContextSliceRecordSchema,
  CritiqueResultRecordSchema,
  DispatchInstructionSchema,
  CurrentSkillExecutionRecordSchema,
  GovernanceReportRecordSchema,
  GovernanceScoreRecordSchema,
  ManagerPlanSchema,
  MicroLoopStateRecordSchema,
  ReviewRecordSchema,
  SpecialistFindingRecordSchema,
  SpecialistLeadRecordSchema,
  SpecialistSupportRecordSchema
} from './tasking-orchestration';
import {
  ChatRouteRecordSchema,
  ExecutionStepRecordSchema,
  LlmUsageRecordSchema,
  ModelRouteDecisionSchema,
  PendingActionRecordSchema,
  PendingApprovalRecordSchema,
  QueueStateRecordSchema,
  WorkflowPresetDefinitionSchema
} from './primitives';
import {
  EntryDecisionRecordSchema,
  ExecutionPlanRecordSchema,
  PartialAggregationRecordSchema,
  PlanDraftRecordSchema,
  PlanModeTransitionRecordSchema
} from './tasking-planning';
import { TaskBackgroundLearningStateSchema, TaskModeGateStateSchema } from './tasking-runtime-state';

export const TaskRecordSchema = z.object({
  id: z.string(),
  goal: z.string(),
  context: z.string().optional(),
  status: z.enum(['queued', 'running', 'waiting_approval', 'blocked', 'cancelled', 'completed', 'failed']),
  sessionId: z.string().optional(),
  runId: z.string().optional(),
  traceId: z.string().optional(),
  skillId: z.string().optional(),
  skillStage: z.string().optional(),
  resolvedWorkflow: WorkflowPresetDefinitionSchema.optional(),
  subgraphTrail: z.array(z.string()).optional(),
  currentNode: z.string().optional(),
  currentMinistry: z.string().optional(),
  currentWorker: z.string().optional(),
  specialistLead: SpecialistLeadRecordSchema.optional(),
  supportingSpecialists: z.array(SpecialistSupportRecordSchema).optional(),
  specialistFindings: z.array(SpecialistFindingRecordSchema).optional(),
  routeConfidence: z.number().optional(),
  contextSlicesBySpecialist: z.array(ContextSliceRecordSchema).optional(),
  dispatches: z.array(DispatchInstructionSchema).optional(),
  critiqueResult: CritiqueResultRecordSchema.optional(),
  chatRoute: ChatRouteRecordSchema.optional(),
  executionSteps: z.array(ExecutionStepRecordSchema).optional(),
  currentExecutionStep: ExecutionStepRecordSchema.optional(),
  queueState: QueueStateRecordSchema.optional(),
  pendingAction: PendingActionRecordSchema.optional(),
  pendingApproval: PendingApprovalRecordSchema.optional(),
  approvalFeedback: z.string().optional(),
  modelRoute: z.array(ModelRouteDecisionSchema).optional(),
  currentStep: z.string().optional(),
  retryCount: z.number().optional(),
  maxRetries: z.number().optional(),
  revisionCount: z.number().optional(),
  maxRevisions: z.number().optional(),
  microLoopCount: z.number().optional(),
  maxMicroLoops: z.number().optional(),
  microLoopState: MicroLoopStateRecordSchema.optional(),
  revisionState: z.enum(['idle', 'needs_revision', 'revising', 'blocked', 'completed']).optional(),
  trace: z.array(z.any()),
  approvals: z.array(ApprovalRecordSchema),
  result: z.string().optional(),
  plan: ManagerPlanSchema.optional(),
  entryDecision: EntryDecisionRecordSchema.optional(),
  executionPlan: ExecutionPlanRecordSchema.optional(),
  budgetGateState: BudgetGateStateRecordSchema.optional(),
  complexTaskPlan: ComplexTaskPlanRecordSchema.optional(),
  blackboardState: BlackboardStateRecordSchema.optional(),
  mainChainNode: z.string().optional(),
  modeGateState: TaskModeGateStateSchema.optional(),
  contextFilterState: z.any().optional(),
  guardrailState: z.any().optional(),
  criticState: z.any().optional(),
  sandboxState: z.any().optional(),
  finalReviewState: z.any().optional(),
  governanceScore: GovernanceScoreRecordSchema.optional(),
  governanceReport: GovernanceReportRecordSchema.optional(),
  libuEvaluationReportId: z.string().optional(),
  evaluationReport: z.any().optional(),
  planMode: z.enum(['intent', 'implementation', 'finalized', 'aborted']).optional(),
  executionMode: z.enum(['standard', 'planning-readonly', 'plan', 'execute', 'imperial_direct']).optional(),
  partialAggregation: PartialAggregationRecordSchema.optional(),
  internalSubAgents: z.array(z.any()).optional(),
  interruptOrigin: z.enum(['counselor_proxy', 'runtime', 'timeout', 'budget', 'review']).optional(),
  planModeTransitions: z.array(PlanModeTransitionRecordSchema).optional(),
  planDraft: PlanDraftRecordSchema.optional(),
  agentStates: z.array(AgentExecutionStateSchema),
  messages: z.array(AgentMessageRecordSchema),
  review: ReviewRecordSchema.optional(),
  learningCandidates: z.array(LearningCandidateRecordSchema).optional(),
  externalSources: z.array(EvidenceRecordSchema).optional(),
  reusedMemories: z.array(z.string()).optional(),
  reusedRules: z.array(z.string()).optional(),
  reusedSkills: z.array(z.string()).optional(),
  usedInstalledSkills: z.array(z.string()).optional(),
  usedCompanyWorkers: z.array(z.string()).optional(),
  connectorRefs: z.array(z.string()).optional(),
  budgetState: z.any().optional(),
  knowledgeIngestionState: z.any().optional(),
  knowledgeIndexState: z.any().optional(),
  llmUsage: LlmUsageRecordSchema.optional(),
  currentSkillExecution: CurrentSkillExecutionRecordSchema.optional(),
  learningQueueItemId: z.string().optional(),
  backgroundLearningState: TaskBackgroundLearningStateSchema.optional(),
  createdAt: z.string(),
  updatedAt: z.string()
});

export type TaskRecord = z.infer<typeof TaskRecordSchema>;
