import type { ToolDefinition } from '@agent/core';

export const MCP_TOOL_DEFINITIONS: ToolDefinition[] = [
  {
    name: 'browse_page',
    description: 'Open and inspect a target page through a browser automation MCP capability.',
    family: 'mcp',
    category: 'action',
    riskLevel: 'high',
    requiresApproval: true,
    timeoutMs: 15000,
    sandboxProfile: 'browser-automation',
    ownerType: 'shared',
    preferredMinistries: ['bingbu-ops', 'hubu-search'],
    capabilityType: 'mcp-capability',
    isReadOnly: true,
    isConcurrencySafe: false,
    isDestructive: false,
    supportsStreamingDispatch: false,
    permissionScope: 'external-side-effect',
    inputSchema: { type: 'object', properties: { url: { type: 'string' }, goal: { type: 'string' } } }
  },
  {
    name: 'run_terminal',
    description: 'Execute a controlled terminal command inside the sandboxed environment.',
    family: 'mcp',
    category: 'action',
    riskLevel: 'high',
    requiresApproval: true,
    timeoutMs: 15000,
    sandboxProfile: 'workspace-write',
    ownerType: 'shared',
    preferredMinistries: ['bingbu-ops', 'gongbu-code'],
    capabilityType: 'mcp-capability',
    isReadOnly: false,
    isConcurrencySafe: false,
    isDestructive: true,
    supportsStreamingDispatch: false,
    permissionScope: 'workspace-write',
    inputSchema: { type: 'object', properties: { command: { type: 'string' }, goal: { type: 'string' } } }
  },
  {
    name: 'ship_release',
    description: 'Prepare or simulate a release workflow through the release MCP capability.',
    family: 'mcp',
    category: 'action',
    riskLevel: 'critical',
    requiresApproval: true,
    timeoutMs: 20000,
    sandboxProfile: 'release-ops',
    ownerType: 'shared',
    preferredMinistries: ['bingbu-ops', 'xingbu-review'],
    capabilityType: 'mcp-capability',
    isReadOnly: false,
    isConcurrencySafe: false,
    isDestructive: true,
    supportsStreamingDispatch: false,
    permissionScope: 'governance',
    inputSchema: { type: 'object', properties: { target: { type: 'string' }, goal: { type: 'string' } } }
  }
];
