import type { ToolDefinition } from '@agent/runtime';

export const RUNTIME_GOVERNANCE_TOOL_DEFINITIONS: ToolDefinition[] = [
  {
    name: 'archive_thread',
    description: 'Archive a completed thread or task after approval.',
    family: 'runtime-governance',
    category: 'action',
    riskLevel: 'medium',
    requiresApproval: true,
    timeoutMs: 5000,
    sandboxProfile: 'workspace-write',
    ownerType: 'ministry-owned',
    ownerId: 'bingbu-ops',
    preferredMinistries: ['bingbu-ops', 'libu-delivery'],
    capabilityType: 'governance-tool',
    isReadOnly: false,
    isConcurrencySafe: false,
    isDestructive: false,
    supportsStreamingDispatch: false,
    permissionScope: 'governance',
    inputSchema: { type: 'object', properties: { sessionId: { type: 'string' }, reason: { type: 'string' } } }
  },
  {
    name: 'schedule_cancel',
    description: 'Cancel an in-flight scheduled run after approval.',
    family: 'runtime-governance',
    category: 'action',
    riskLevel: 'high',
    requiresApproval: true,
    timeoutMs: 5000,
    sandboxProfile: 'workspace-write',
    ownerType: 'ministry-owned',
    ownerId: 'bingbu-ops',
    preferredMinistries: ['bingbu-ops'],
    capabilityType: 'governance-tool',
    isReadOnly: false,
    isConcurrencySafe: false,
    isDestructive: true,
    supportsStreamingDispatch: false,
    permissionScope: 'governance',
    inputSchema: { type: 'object', properties: { runId: { type: 'string' }, reason: { type: 'string' } } }
  },
  {
    name: 'recover_run',
    description: 'Recover a paused or blocked run with governance metadata.',
    family: 'runtime-governance',
    category: 'action',
    riskLevel: 'medium',
    requiresApproval: true,
    timeoutMs: 5000,
    sandboxProfile: 'workspace-write',
    ownerType: 'ministry-owned',
    ownerId: 'bingbu-ops',
    preferredMinistries: ['bingbu-ops'],
    capabilityType: 'governance-tool',
    isReadOnly: false,
    isConcurrencySafe: false,
    isDestructive: false,
    supportsStreamingDispatch: false,
    permissionScope: 'governance',
    inputSchema: { type: 'object', properties: { runId: { type: 'string' }, checkpointId: { type: 'string' } } }
  },
  {
    name: 'list_runtime_artifacts',
    description: 'List runtime artifacts such as schedules, archives, and browser replays.',
    family: 'runtime-governance',
    category: 'knowledge',
    riskLevel: 'low',
    requiresApproval: false,
    timeoutMs: 5000,
    sandboxProfile: 'workspace-readonly',
    ownerType: 'ministry-owned',
    ownerId: 'bingbu-ops',
    preferredMinistries: ['bingbu-ops', 'libu-delivery'],
    capabilityType: 'governance-tool',
    isReadOnly: true,
    isConcurrencySafe: true,
    isDestructive: false,
    supportsStreamingDispatch: true,
    permissionScope: 'readonly',
    inputSchema: { type: 'object', properties: { kind: { type: 'string' } } }
  }
];
