const fallbackLabels: Record<string, string> = {
  'ai_providers.title': 'AI 提供商配置',
  'ai_providers.gemini_title': 'Gemini API 密钥',
  'ai_providers.gemini_add_button': '添加密钥',
  'ai_providers.gemini_empty_title': '暂无Gemini密钥',
  'ai_providers.gemini_empty_desc': '点击上方按钮添加第一个密钥',
  'ai_providers.codex_title': 'Codex API 配置',
  'ai_providers.codex_add_button': '添加配置',
  'ai_providers.codex_empty_title': '暂无Codex配置',
  'ai_providers.codex_empty_desc': '点击上方按钮添加第一个配置',
  'ai_providers.claude_title': 'Claude API 配置',
  'ai_providers.claude_add_button': '添加配置',
  'ai_providers.claude_empty_title': '暂无Claude配置',
  'ai_providers.claude_empty_desc': '点击上方按钮添加第一个配置',
  'ai_providers.vertex_title': 'Vertex API 配置',
  'ai_providers.vertex_add_button': '导入配置',
  'ai_providers.vertex_empty_title': '暂无Vertex配置',
  'ai_providers.vertex_empty_desc': '点击上方按钮导入服务账号配置',
  'ai_providers.openai_title': 'OpenAI 兼容配置',
  'ai_providers.openai_add_button': '添加配置',
  'ai_providers.openai_empty_title': '暂无OpenAI兼容配置',
  'ai_providers.openai_empty_desc': '点击上方按钮添加第一个兼容端点',
  'ai_providers.ampcode_title': 'Ampcode 桥接配置',
  'common.add': '添加',
  'common.api_key': 'API Key',
  'common.base_url': 'Base URL',
  'common.delete': '删除',
  'common.edit': '编辑',
  'common.loading': '加载中',
  'common.close': '关闭',
  'common.copy': '复制',
  'common.no': '否',
  'common.not_set': '未设置',
  'common.yes': '是',
  'common.prefix': 'Prefix',
  'common.priority': 'Priority',
  'common.proxy_url': 'Proxy URL',
  'auth_files.batch_deselect': '取消选择',
  'auth_files.batch_select_all': '选择',
  'auth_files.delete_button': '删除',
  'auth_files.download_button': '下载',
  'auth_files.file_modified': '修改时间',
  'auth_files.file_size': '大小',
  'auth_files.filter_all': '全部',
  'auth_files.filter_antigravity': 'Antigravity',
  'auth_files.filter_claude': 'Claude',
  'auth_files.filter_codex': 'Codex',
  'auth_files.filter_gemini': 'Gemini',
  'auth_files.filter_gemini-cli': 'Gemini CLI',
  'auth_files.filter_kimi': 'Kimi',
  'auth_files.filter_qwen': 'Qwen',
  'auth_files.filter_vertex': 'Vertex',
  'auth_files.health_status_disabled': '已停用',
  'auth_files.health_status_healthy': '启用',
  'auth_files.health_status_label': '健康状态',
  'auth_files.health_status_warning': '异常',
  'auth_files.models_button': '模型',
  'auth_files.models_empty': '暂无模型',
  'auth_files.models_empty_desc': '当前认证文件暂未返回可用模型。',
  'auth_files.models_excluded_badge': '已排除',
  'auth_files.models_excluded_hint': '该模型已在排除列表中。',
  'auth_files.models_loading': '正在加载模型',
  'auth_files.models_title': '可用模型',
  'auth_files.models_unsupported': '不支持模型列举',
  'auth_files.models_unsupported_desc': '当前认证文件类型暂不支持模型列举。',
  'auth_files.note_display': '备注',
  'auth_files.prefix_proxy_button': '字段修补',
  'auth_files.priority_display': '优先级',
  'auth_files.quota_runtime_placeholder': '额度信息待同步',
  'auth_files.status_toggle_label': '状态切换',
  'auth_files.type_virtual': '虚拟认证文件',
  'status_bar.failure_short': '失败',
  'status_bar.no_requests': '--',
  'status_bar.success_short': '成功',
  'stats.failure': '失败',
  'stats.success': '成功'
};

export type LabelFunction = (key: string, options?: Record<string, unknown>) => string;

export const label: LabelFunction = (key, options) => {
  if (typeof options?.defaultValue === 'string') return options.defaultValue;
  return fallbackLabels[key] ?? (typeof options?.count === 'number' ? `${key}: ${options.count}` : key);
};
