import type { FeedSourceRecord } from './briefing-sources';

export const AI_FEED_SOURCES: FeedSourceRecord[] = [
  {
    id: 'openai-news',
    category: 'ai-tech',
    name: 'OpenAI News',
    sourceUrl: 'https://openai.com/news/',
    feedUrl: 'https://openai.com/news/rss.xml',
    sourceType: 'rss',
    authorityTier: 'official-blog',
    sourceGroup: 'official',
    contentKind: 'release',
    parserKind: 'feed',
    topicTags: ['ai', 'model', 'api', 'agent']
  },
  {
    id: 'huggingface-blog',
    category: 'ai-tech',
    name: 'Hugging Face Blog',
    sourceUrl: 'https://huggingface.co/blog',
    feedUrl: 'https://huggingface.co/blog/feed.xml',
    sourceType: 'atom',
    authorityTier: 'official-blog',
    sourceGroup: 'official',
    contentKind: 'release',
    parserKind: 'feed',
    topicTags: ['ai', 'open-source', 'agent', 'workflow']
  },
  {
    id: 'google-ai-blog',
    category: 'ai-tech',
    name: 'Google AI Blog',
    sourceUrl: 'https://blog.google/technology/ai/',
    feedUrl: 'https://blog.google/technology/ai/rss/',
    sourceType: 'rss',
    authorityTier: 'official-blog',
    sourceGroup: 'official',
    contentKind: 'release',
    parserKind: 'feed',
    topicTags: ['ai', 'model', 'research']
  },
  {
    id: 'anthropic-news',
    category: 'ai-tech',
    name: 'Anthropic News',
    sourceUrl: 'https://www.anthropic.com/news',
    feedUrl: 'https://www.anthropic.com/news/rss.xml',
    sourceType: 'rss',
    authorityTier: 'official-blog',
    sourceGroup: 'official',
    contentKind: 'release',
    parserKind: 'feed',
    topicTags: ['ai', 'api', 'agent']
  },
  {
    id: 'mistral-news',
    category: 'ai-tech',
    name: 'Mistral News',
    sourceUrl: 'https://mistral.ai/news/',
    feedUrl: 'https://mistral.ai/news/rss.xml',
    sourceType: 'rss',
    authorityTier: 'official-blog',
    sourceGroup: 'official',
    contentKind: 'release',
    parserKind: 'feed',
    topicTags: ['ai', 'model', 'inference']
  },
  {
    id: 'langchain-blog',
    category: 'ai-tech',
    name: 'LangChain Blog',
    sourceUrl: 'https://blog.langchain.com/',
    feedUrl: 'https://blog.langchain.com/rss/',
    sourceType: 'rss',
    authorityTier: 'official-blog',
    sourceGroup: 'official',
    contentKind: 'docs-update',
    parserKind: 'feed',
    topicTags: ['ai', 'langchain', 'framework', 'workflow']
  },
  {
    id: 'vercel-ai-sdk',
    category: 'ai-tech',
    name: 'Vercel AI SDK',
    sourceUrl: 'https://vercel.com/changelog',
    feedUrl: 'https://vercel.com/changelog/rss.xml',
    sourceType: 'rss',
    authorityTier: 'official-release',
    sourceGroup: 'official',
    contentKind: 'release',
    parserKind: 'feed',
    topicTags: ['ai', 'sdk', 'api', 'vercel']
  },
  {
    id: 'latent-space',
    category: 'ai-tech',
    name: 'Latent Space',
    sourceUrl: 'https://www.latent.space/',
    feedUrl: 'https://www.latent.space/rss/',
    sourceType: 'rss',
    authorityTier: 'top-tier-media',
    sourceGroup: 'authority',
    contentKind: 'benchmark',
    parserKind: 'feed',
    topicTags: ['ai', 'benchmark', 'media']
  },
  {
    id: 'simon-willison-weblog',
    category: 'ai-tech',
    name: 'Simon Willison Blog',
    sourceUrl: 'https://simonwillison.net/',
    feedUrl: 'https://simonwillison.net/atom/everything/',
    sourceType: 'atom',
    authorityTier: 'top-tier-media',
    sourceGroup: 'authority',
    contentKind: 'docs-update',
    parserKind: 'feed',
    topicTags: ['ai', 'agent', 'tooling']
  },
  {
    id: 'hacker-news-ai',
    category: 'ai-tech',
    name: 'Hacker News / AI',
    sourceUrl: 'https://news.ycombinator.com/',
    feedUrl: 'https://hnrss.org/newest?q=AI+agent+LLM+OpenAI+Anthropic+LangChain&points=50',
    sourceType: 'rss',
    authorityTier: 'top-tier-media',
    sourceGroup: 'community',
    contentKind: 'community-discussion',
    parserKind: 'community-post',
    topicTags: ['ai', 'community']
  }
];
