import type { SecurityPageSourceRecord } from './briefing-sources';

export const FRONTEND_SECURITY_PAGE_SOURCES_DATA: SecurityPageSourceRecord[] = [
  {
    id: 'nodejs-security-page',
    category: 'general-security',
    name: 'Node.js Security',
    sourceUrl: 'https://nodejs.org/',
    pageUrl: 'https://nodejs.org/en/blog/vulnerability/april-2026-security-releases',
    sourceType: 'official-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['general-security', 'nodejs', 'runtime']
  },
  {
    id: 'postgresql-security-page',
    category: 'general-security',
    name: 'PostgreSQL Security',
    sourceUrl: 'https://www.postgresql.org/',
    pageUrl: 'https://www.postgresql.org/support/security/CVE-2026-postgresql-high-risk/',
    sourceType: 'official-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['general-security', 'postgresql', 'database']
  },
  {
    id: 'redis-security-page',
    category: 'general-security',
    name: 'Redis Security',
    sourceUrl: 'https://redis.io/',
    pageUrl: 'https://redis.io/security/advisories/redis-rce-april-2026/',
    sourceType: 'official-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['general-security', 'redis', 'database']
  },
  {
    id: 'kubernetes-security-page',
    category: 'general-security',
    name: 'Kubernetes Security',
    sourceUrl: 'https://kubernetes.io/',
    pageUrl: 'https://kubernetes.io/blog/2026/03/31/security-advisory-kubernetes-rbac-bypass/',
    sourceType: 'official-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['general-security', 'kubernetes', 'rbac']
  },
  {
    id: 'docker-security-page',
    category: 'general-security',
    name: 'Docker Security',
    sourceUrl: 'https://www.docker.com/',
    pageUrl: 'https://www.docker.com/blog/docker-engine-security-bulletin-april-2026/',
    sourceType: 'official-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['general-security', 'docker', 'container']
  },
  {
    id: 'linux-kernel-security-page',
    category: 'general-security',
    name: 'Linux Kernel Security',
    sourceUrl: 'https://www.kernel.org/',
    pageUrl: 'https://www.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.14.3',
    sourceType: 'official-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['general-security', 'linux', 'kernel']
  },
  {
    id: 'microsoft-security-response-center',
    category: 'general-security',
    name: 'Microsoft Security Response Center',
    sourceUrl: 'https://msrc.microsoft.com/',
    pageUrl: 'https://msrc.microsoft.com/update-guide/vulnerability/CVE-2026-windows-privilege-boundary',
    sourceType: 'official-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['general-security', 'windows', 'privilege']
  },
  {
    id: 'apple-security-updates',
    category: 'general-security',
    name: 'Apple Security Updates',
    sourceUrl: 'https://support.apple.com/',
    pageUrl: 'https://support.apple.com/en-us/122000',
    sourceType: 'official-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['general-security', 'macos', 'apple']
  },
  {
    id: 'aws-security-bulletins',
    category: 'general-security',
    name: 'AWS Security Bulletins',
    sourceUrl: 'https://aws.amazon.com/security/security-bulletins/',
    pageUrl: 'https://aws.amazon.com/security/security-bulletins/AWS-2026-004/',
    sourceType: 'official-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['general-security', 'aws', 'cloud']
  },
  {
    id: 'axios-github-advisory',
    category: 'frontend-security',
    name: 'GitHub Advisory / axios',
    sourceUrl: 'https://github.com/advisories',
    pageUrl: 'https://github.com/advisories/GHSA-4hjh-wcwx-xvwj',
    sourceType: 'security-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'github-advisory',
    parserKind: 'security-advisory',
    topicTags: ['frontend-security', 'axios', 'advisory']
  },
  {
    id: 'claude-code-workspace-trust-gitlab',
    category: 'devtool-security',
    name: 'GitLab Advisory / Claude Code',
    sourceUrl: 'https://advisories.gitlab.com/pkg/npm/%40anthropic-ai/claude-code/',
    pageUrl: 'https://advisories.gitlab.com/pkg/npm/%40anthropic-ai/claude-code/CVE-2026-33068/',
    sourceType: 'security-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'gitlab-advisory',
    parserKind: 'security-advisory',
    topicTags: ['devtool-security', 'claude-code', 'advisory']
  },
  {
    id: 'mcp-path-traversal-github-advisory',
    category: 'devtool-security',
    name: 'GitHub Advisory / MCP Server',
    sourceUrl: 'https://github.com/advisories',
    pageUrl: 'https://github.com/advisories/GHSA-mcp-path-traversal-2026',
    sourceType: 'security-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'github-advisory',
    parserKind: 'security-advisory',
    topicTags: ['devtool-security', 'mcp', 'path-traversal']
  },
  {
    id: 'langgraph-checkpointer-security',
    category: 'devtool-security',
    name: 'LangChain Security Blog',
    sourceUrl: 'https://blog.langchain.com/',
    pageUrl: 'https://blog.langchain.com/langgraph-memory-checkpoint-vulnerability',
    sourceType: 'official-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['devtool-security', 'langgraph', 'checkpointer', 'memory']
  },
  {
    id: 'huggingface-spaces-env-security',
    category: 'devtool-security',
    name: 'Hugging Face Security',
    sourceUrl: 'https://huggingface.co/blog',
    pageUrl: 'https://huggingface.co/blog/spaces-env-exposure-security',
    sourceType: 'official-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['devtool-security', 'hugging-face', 'spaces', 'env']
  },
  {
    id: 'langsmith-permission-fix',
    category: 'devtool-security',
    name: 'LangSmith Changelog',
    sourceUrl: 'https://docs.smith.langchain.com/changelog',
    pageUrl: 'https://docs.smith.langchain.com/changelog/team-project-permission-fix',
    sourceType: 'official-page',
    authorityTier: 'official-blog',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['devtool-security', 'langsmith', 'permissions']
  },
  {
    id: 'apifox-official-incident',
    category: 'frontend-security',
    name: 'Apifox 官方公告',
    sourceUrl: 'https://apifox.com',
    pageUrl: 'https://docs.apifox.com/8392582m0',
    sourceType: 'official-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'incident',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['frontend-security', 'apifox', 'cdn']
  },
  {
    id: 'nodejs-security-releases',
    category: 'frontend-security',
    name: 'Node.js Official',
    sourceUrl: 'https://nodejs.org/',
    pageUrl: 'https://nodejs.org/en/blog/vulnerability/march-2026-security-releases',
    sourceType: 'official-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['frontend-security', 'nodejs', 'runtime', 'ssr']
  },
  {
    id: 'chrome-releases-security',
    category: 'frontend-security',
    name: 'Chrome Releases',
    sourceUrl: 'https://chromereleases.googleblog.com/',
    pageUrl: 'https://chromereleases.googleblog.com/2026/03/stable-channel-update-for-desktop_31.html',
    sourceType: 'official-page',
    authorityTier: 'official-advisory',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['frontend-security', 'chrome', 'browser', 'webgl', 'webcodecs']
  },
  {
    id: 'v8-wasm-security-fix',
    category: 'frontend-security',
    name: 'V8 Dev Blog',
    sourceUrl: 'https://v8.dev/blog',
    pageUrl: 'https://v8.dev/blog/wasm-memory-corruption-fix',
    sourceType: 'official-page',
    authorityTier: 'official-blog',
    sourceGroup: 'official',
    contentKind: 'advisory',
    pageKind: 'incident-page',
    parserKind: 'incident-page',
    topicTags: ['frontend-security', 'v8', 'wasm', 'webassembly']
  },
  {
    id: 'claude-code-source-map-exposure',
    category: 'devtool-security',
    name: 'The Verge / Claude Code 源码泄露',
    sourceUrl: 'https://www.theverge.com/',
    pageUrl: 'https://www.theverge.com/ai-artificial-intelligence/904776/anthropic-claude-source-code-leak',
    sourceType: 'official-page',
    authorityTier: 'top-tier-media',
    sourceGroup: 'authority',
    contentKind: 'incident',
    pageKind: 'media-incident',
    parserKind: 'media-report',
    topicTags: ['devtool-security', 'claude-code', 'source-map', 'toolchain']
  },
  {
    id: 'axios-datadog-security-labs',
    category: 'frontend-security',
    name: 'Datadog Security Labs / axios',
    sourceUrl: 'https://securitylabs.datadoghq.com/',
    pageUrl: 'https://securitylabs.datadoghq.com/articles/axios-npm-supply-chain-compromise/',
    sourceType: 'security-page',
    authorityTier: 'top-tier-media',
    sourceGroup: 'authority',
    contentKind: 'incident',
    pageKind: 'media-incident',
    parserKind: 'media-report',
    topicTags: ['frontend-security', 'axios', 'supply-chain']
  },
  {
    id: 'axios-bitdefender-advisory',
    category: 'frontend-security',
    name: 'Bitdefender Technical Advisory / axios',
    sourceUrl: 'https://businessinsights.bitdefender.com/',
    pageUrl:
      'https://businessinsights.bitdefender.com/technical-advisory-axios-npm-supply-chain-attack-cross-platform-rat-deployed-compromised-account',
    sourceType: 'security-page',
    authorityTier: 'top-tier-media',
    sourceGroup: 'authority',
    contentKind: 'incident',
    pageKind: 'media-incident',
    parserKind: 'media-report',
    topicTags: ['frontend-security', 'axios', 'supply-chain']
  },
  {
    id: 'axios-cn-sec-report',
    category: 'frontend-security',
    name: 'CN-SEC / axios 供应链投毒',
    sourceUrl: 'https://cn-sec.com/',
    pageUrl: 'https://cn-sec.com/archives/5140833.html',
    sourceType: 'security-page',
    authorityTier: 'top-tier-media',
    sourceGroup: 'authority',
    contentKind: 'incident',
    pageKind: 'media-incident',
    parserKind: 'media-report',
    topicTags: ['frontend-security', 'axios', 'supply-chain']
  },
  {
    id: 'axios-ithome-report',
    category: 'frontend-security',
    name: 'IT之家 / axios 供应链攻击',
    sourceUrl: 'https://www.ithome.com/',
    pageUrl: 'https://finance.sina.com.cn/tech/digi/2026-03-31/doc-inhswicu3324323.shtml',
    sourceType: 'security-page',
    authorityTier: 'top-tier-media',
    sourceGroup: 'authority',
    contentKind: 'incident',
    pageKind: 'media-incident',
    parserKind: 'media-report',
    topicTags: ['frontend-security', 'axios', 'supply-chain']
  }
];
