import type { FeedSourceRecord } from './briefing-sources';

export const FRONTEND_FEED_SOURCES: FeedSourceRecord[] = [
  {
    id: 'react-blog',
    category: 'frontend-tech',
    name: 'React Blog',
    sourceUrl: 'https://react.dev/blog',
    feedUrl: 'https://react.dev/feed.xml',
    sourceType: 'atom',
    authorityTier: 'official-blog',
    sourceGroup: 'official',
    contentKind: 'release',
    parserKind: 'feed',
    topicTags: ['frontend', 'react', 'rsc']
  },
  {
    id: 'vite-blog',
    category: 'frontend-tech',
    name: 'Vite Blog',
    sourceUrl: 'https://vite.dev/blog/',
    feedUrl: 'https://vite.dev/blog.rss',
    sourceType: 'rss',
    authorityTier: 'official-release',
    sourceGroup: 'official',
    contentKind: 'release',
    parserKind: 'feed',
    topicTags: ['frontend', 'vite', 'bundler']
  },
  {
    id: 'vue-blog',
    category: 'frontend-tech',
    name: 'Vue Blog',
    sourceUrl: 'https://blog.vuejs.org/',
    feedUrl: 'https://blog.vuejs.org/feed.xml',
    sourceType: 'atom',
    authorityTier: 'official-blog',
    sourceGroup: 'official',
    contentKind: 'release',
    parserKind: 'feed',
    topicTags: ['frontend', 'vue', 'framework']
  },
  {
    id: 'typescript-blog',
    category: 'frontend-tech',
    name: 'TypeScript Blog',
    sourceUrl: 'https://devblogs.microsoft.com/typescript/',
    feedUrl: 'https://devblogs.microsoft.com/typescript/feed/',
    sourceType: 'rss',
    authorityTier: 'official-blog',
    sourceGroup: 'official',
    contentKind: 'release',
    parserKind: 'feed',
    topicTags: ['frontend', 'typescript', 'language']
  },
  {
    id: 'eslint-blog',
    category: 'frontend-tech',
    name: 'ESLint Blog',
    sourceUrl: 'https://eslint.org/blog/',
    feedUrl: 'https://eslint.org/feed.xml',
    sourceType: 'rss',
    authorityTier: 'official-release',
    sourceGroup: 'official',
    contentKind: 'release',
    parserKind: 'feed',
    topicTags: ['frontend', 'eslint', 'tooling']
  },
  {
    id: 'astro-blog',
    category: 'frontend-tech',
    name: 'Astro Blog',
    sourceUrl: 'https://astro.build/blog/',
    feedUrl: 'https://astro.build/rss.xml',
    sourceType: 'rss',
    authorityTier: 'official-blog',
    sourceGroup: 'official',
    contentKind: 'release',
    parserKind: 'feed',
    topicTags: ['frontend', 'astro', 'ssr', 'vite']
  },
  {
    id: 'nextjs-blog',
    category: 'frontend-tech',
    name: 'Next.js Blog',
    sourceUrl: 'https://nextjs.org/blog',
    feedUrl: 'https://nextjs.org/feed.xml',
    sourceType: 'rss',
    authorityTier: 'official-release',
    sourceGroup: 'official',
    contentKind: 'release',
    parserKind: 'feed',
    topicTags: ['frontend', 'nextjs', 'ssr', 'adapter']
  },
  {
    id: 'web-dev',
    category: 'frontend-tech',
    name: 'web.dev',
    sourceUrl: 'https://web.dev/blog/',
    feedUrl: 'https://web.dev/feed.xml',
    sourceType: 'rss',
    authorityTier: 'top-tier-media',
    sourceGroup: 'authority',
    contentKind: 'docs-update',
    parserKind: 'feed',
    topicTags: ['frontend', 'web-api', 'browser']
  },
  {
    id: 'smashing-magazine',
    category: 'frontend-tech',
    name: 'Smashing Magazine',
    sourceUrl: 'https://www.smashingmagazine.com/',
    feedUrl: 'https://www.smashingmagazine.com/feed/',
    sourceType: 'rss',
    authorityTier: 'top-tier-media',
    sourceGroup: 'authority',
    contentKind: 'docs-update',
    parserKind: 'feed',
    topicTags: ['frontend', 'css', 'design-system', 'browser']
  },
  {
    id: 'css-tricks',
    category: 'frontend-tech',
    name: 'CSS-Tricks',
    sourceUrl: 'https://css-tricks.com/',
    feedUrl: 'https://css-tricks.com/feed/',
    sourceType: 'rss',
    authorityTier: 'top-tier-media',
    sourceGroup: 'authority',
    contentKind: 'docs-update',
    parserKind: 'feed',
    topicTags: ['frontend', 'css', 'browser']
  },
  {
    id: 'frontend-focus',
    category: 'frontend-tech',
    name: 'Frontend Focus',
    sourceUrl: 'https://frontendfoc.us/',
    feedUrl: 'https://frontendfoc.us/rss',
    sourceType: 'rss',
    authorityTier: 'top-tier-media',
    sourceGroup: 'authority',
    contentKind: 'docs-update',
    parserKind: 'feed',
    topicTags: ['frontend', 'weekly', 'tooling']
  },
  {
    id: 'chrome-developers-blog',
    category: 'frontend-tech',
    name: 'Chrome Developers',
    sourceUrl: 'https://developer.chrome.com/blog',
    feedUrl: 'https://developer.chrome.com/blog/feed.xml',
    sourceType: 'rss',
    authorityTier: 'official-blog',
    sourceGroup: 'official',
    contentKind: 'docs-update',
    parserKind: 'feed',
    topicTags: ['frontend', 'browser', 'chrome']
  },
  {
    id: 'cloudflare-blog',
    category: 'frontend-tech',
    name: 'Cloudflare Blog',
    sourceUrl: 'https://blog.cloudflare.com/',
    feedUrl: 'https://blog.cloudflare.com/rss/',
    sourceType: 'rss',
    authorityTier: 'top-tier-media',
    sourceGroup: 'authority',
    contentKind: 'docs-update',
    parserKind: 'feed',
    topicTags: ['frontend', 'edge', 'platform']
  },
  {
    id: 'vercel-blog',
    category: 'frontend-tech',
    name: 'Vercel Blog',
    sourceUrl: 'https://vercel.com/blog',
    feedUrl: 'https://vercel.com/blog/rss.xml',
    sourceType: 'rss',
    authorityTier: 'top-tier-media',
    sourceGroup: 'authority',
    contentKind: 'docs-update',
    parserKind: 'feed',
    topicTags: ['frontend', 'nextjs', 'deployment']
  },
  {
    id: 'hacker-news-frontend',
    category: 'frontend-tech',
    name: 'Hacker News / Frontend',
    sourceUrl: 'https://news.ycombinator.com/',
    feedUrl: 'https://hnrss.org/newest?q=React+Vite+Next.js+TypeScript+Web+Platform&points=40',
    sourceType: 'rss',
    authorityTier: 'top-tier-media',
    sourceGroup: 'community',
    contentKind: 'community-discussion',
    parserKind: 'community-post',
    topicTags: ['frontend', 'community']
  }
];
