/**
 * Centers facade — platform-runtime 投影能力的后端访问入口。
 *
 * 后端业务代码必须通过此文件访问 @agent/platform-runtime 的 centers 导出，
 * 不允许直接引用 @agent/platform-runtime（详见包边界规则脚本）。
 */
export {
  fetchProviderUsageAudit,
  fetchProviderUsageAuditFromAdapter,
  normalizeProviderAuditResponse,
  summarizeProviderBilling,
  type ProviderAuditAdapterConfig,
  type ProviderAuditDailyRecord,
  type ProviderAuditSyncResult,
  buildModelHeatmap,
  buildTraceAnalytics,
  formatDay,
  roundCurrency,
  summarizeUsageAnalytics,
  buildRuntimeCenterProjection,
  buildRuntimeCenterSummaryProjection,
  toCritiqueStyleReviewOutcome,
  type RuntimeCenterTaskLike,
  buildLearningCenter,
  buildLearningCenterSummary,
  buildRuntimeWorkspaceCenter,
  type BuildLearningCenterInput,
  type BuildRuntimeWorkspaceCenterInput,
  type CrossCheckEvidenceEntry,
  type LearningCenterTaskLike,
  type LocalSkillSuggestionsRecord,
  type RecentQuarantinedMemory,
  type RuntimeGovernanceSnapshotRecord,
  buildLearningMemoryStats,
  normalizeLearningCenterJobs,
  normalizeLearningCenterTasks,
  countInvalidatedRules,
  buildCompanyAgentsCenter,
  buildConnectorsCenter,
  type RuntimeConnectorsCenterRecord,
  defaultConnectorSessionState,
  groupConnectorDiscoveryHistory,
  groupGovernanceAuditByTarget,
  type RuntimeConnectorDiscoveryRecord,
  type RuntimeConnectorGovernanceAuditRecord,
  loadConnectorCenterProjection,
  loadConnectorProjectionById,
  type RuntimeConnectorCenterLoaderInput,
  buildSkillSourcesCenter,
  type InstalledSkillRecord,
  type SkillInstallReceiptRecord,
  readPersistedEvalHistory,
  readPersistedUsageAnalytics,
  summarizeAndPersistEvalHistory,
  summarizeAndPersistUsageAnalytics,
  shouldUsePersistedEvalSnapshot,
  shouldUsePersistedUsageSnapshot,
  refreshMetricsSnapshots,
  type RuntimeMetricsRefreshContext,
  filterAndSortRecentRuntimeRuns,
  buildRecentTraceSummaryLines
} from '@agent/platform-runtime';
