export const KNOWLEDGE_REPOSITORY = Symbol('KNOWLEDGE_REPOSITORY');
export const KNOWLEDGE_OSS_STORAGE = Symbol('KNOWLEDGE_OSS_STORAGE');
export const KNOWLEDGE_SDK_RUNTIME = Symbol('KNOWLEDGE_SDK_RUNTIME');
