import type { RuntimeTaskRecord as SharedTaskRecord } from '../runtime/runtime-task.types';

export type SessionTaskAggregate = SharedTaskRecord;

export type SessionTaskLike = Pick<
  SharedTaskRecord,
  | 'activeInterrupt'
  | 'agentStates'
  | 'approvalFeedback'
  | 'approvals'
  | 'backgroundLearningState'
  | 'budgetState'
  | 'context'
  | 'createdAt'
  | 'currentExecutionStep'
  | 'currentMinistry'
  | 'currentNode'
  | 'currentSkillExecution'
  | 'currentStep'
  | 'currentWorker'
  | 'entryDecision'
  | 'executionMode'
  | 'executionPlan'
  | 'executionSteps'
  | 'goal'
  | 'id'
  | 'interruptHistory'
  | 'learningCandidates'
  | 'learningEvaluation'
  | 'learningQueueItemId'
  | 'llmUsage'
  | 'messages'
  | 'modelRoute'
  | 'pendingAction'
  | 'pendingApproval'
  | 'plan'
  | 'planDraft'
  | 'queueState'
  | 'result'
  | 'review'
  | 'runId'
  | 'sessionId'
  | 'status'
  | 'toolUsageSummary'
  | 'trace'
  | 'updatedAt'
>;
